exports.statusCode = {
    "EVERYTHING_IS_OK": 200,
    "NOT_MODIFIED": 304,
    "BAD_REQUEST": 400,
    "PARAMETER_IS_MISSING": 401,
    "FORBIDDEN": 403,
    "NOT_FOUND": 404,
    "ALREADY_EXIST": 409,
    "INTERNAL_SERVER_ERROR": 500,
    "WENT_WRONG": 501,
    "SOMETHING_WENT_WRONG": 503,
    "SESSION_EXPIRED": 440,
}

exports.statusMessage = {
    "ValidationError": "Validation Error.",
    "SOME-THING-WENT-WRONG": "Some went wrong",
    "Login_sucess": "Login successfully",
    "NOT_IN_USE": "NOT IN USE",
    "phonenumber_already": 'This phone number is already in use',
    "Email_already": 'This email is already in use',
    "success": 'Success',
    "NOT_FOUND": "NOT FOUND",
    "PASSWORD_NOT_MATCHED": "Your passowrd not matched with password you were using to login",
    "TOKEN_NOT_FOUND": "Please provide acess token in headers",
    "INVALID_USER": "Account does not exist",
    "INVALID_ACESS_TOKEN": "Invalid acess token provided",
    "DB_ERROR": "Database related error",
    "INVALID_EMAIL": "Account does not exist",
    "WRONG_PASSWORD": "Please enter correct password.",
    "WRONG_OLD_PASSWORD": "The old password you have entered is incorrect.",
    "MOBILE_ALREADY_REGISTERED": "This phone number is already in use",
    "EMAIL_ALREADY_REGISTERED": "This email is already in use",
    "MOBILE_NOT_REGISTERED": "This mobile number is not registered with us.",
    "INCORRECT_OLD_PASSWORD": "The old password you have entered is incorrect.",
    "ADDED": "Added successfully.",
    "UPDATED": "Updated successfully.",
    "DELETED": "Deleted successfully.",
    "INACTIVE_USER": "Your account is either inactive , deleted or blocked . Please contact to customer service.",
}